In [2]:
import requests
import json
import pandas as pd
import os
# 네이버 API 인증 정보
client_id = "x_45StwzjCiPnscCfTqJ"
client_secret = "aOhY7CBjXw"

# 공통 헤더
headers = {
    'X-Naver-Client-Id': client_id,
    'X-Naver-Client-Secret': client_secret
}
os.makedirs('data',exist_ok=True)
# 검색 함수 정의
def search_shops(query):
    url = "https://openapi.naver.com/v1/search/shop.json"
    
    # 쿼리 파라미터 설정
    payload = {
        'query': query,
        'display': 10,
        'sort': 'sim'
    }

    # API 요청
    res = requests.get(url, params=payload, headers=headers)

    # 응답 코드 확인
    if res.status_code == 200:
        items = res.json()['items']
        return items
    else:
        print("Error:", res.status_code)
        return []


# 결과 파싱 예시
shops = search_shops("가디건")
with open('data/shops.json', 'w', encoding='utf-8') as f:
    json.dump(shops, f, ensure_ascii=False, indent=2)
df= pd.read_json('data/shops.json')
df
# 파싱해서 출력
#for book in books:
 #   print("제목:", book['title'])
 #   print("저자:", book['author'])
  #  print("출판사:", book['publisher'])
   # print("링크:", book['link'])
    #print("-" * 40)
#df = pd.read_json('data/books.json')
#df

,title,link,image,lprice,hprice,mallName,productId,productType,brand,maker,category1,category2,category3,category4
0,백화점3-5일배송 폴로 <b>가디건</b> 걸즈 걸스 랄프로렌 꽈배기 블랙 화이트 ...,https://smartstore.naver.com/main/products/667...,https://shopping-phinf.pstatic.net/main_842166...,65900,,나우인뉴욕,84216650390,2,폴로랄프로렌,폴로랄프로렌,패션의류,여성의류,카디건,
1,[백화점3-5일배송] 폴로 <b>가디건</b> 니트 걸즈 랄프로렌 블랙 화이트 핑크...,https://smartstore.naver.com/main/products/845...,https://shopping-phinf.pstatic.net/main_859949...,63900,,트위티 155,85994962324,2,폴로랄프로렌,폴로랄프로렌,패션의류,여성의류,카디건,
2,봄 가을 간절기 라운드 루즈핏 크롭 <b>가디건</b> 레드 그린 핑크 화이트 블랙...,https://smartstore.naver.com/main/products/546...,https://shopping-phinf.pstatic.net/main_830114...,19900,,ARUMY,83011442056,2,,,패션의류,여성의류,카디건,
3,부드러운 캐시미어 크롭 <b>가디건</b> 숏 라운드 니트<b>가디건</b> 여성 ...,https://smartstore.naver.com/main/products/482...,https://shopping-phinf.pstatic.net/main_823726...,18900,,코이블리,82372678315,2,,,패션의류,여성의류,카디건,
4,[백화점] 폴로 <b>가디건</b> 걸즈 케이블 꽈배기 니트,https://smartstore.naver.com/main/products/111...,https://shopping-phinf.pstatic.net/main_886518...,69000,,세컨찬스라이프,88651894622,2,폴로랄프로렌,폴로랄프로렌,패션의류,여성의류,카디건,
5,시스루 얇은 린넨 루즈핏 니트 여름 여성 <b>가디건</b> (올타임),https://smartstore.naver.com/main/products/559...,https://shopping-phinf.pstatic.net/main_831365...,23900,,고고하니,83136576950,2,,,패션의류,여성의류,카디건,
6,(당일) 프리티영띵 뉴 페블 골지 <b>가디건</b> PYT 프영띵 떠유니,https://smartstore.naver.com/main/products/904...,https://shopping-phinf.pstatic.net/main_865893...,42000,,ttoyuni,86589381117,2,,,패션의류,여성의류,카디건,
7,꼼데가르송 기본와펜 <b>가디건</b> 여성용,https://smartstore.naver.com/main/products/474...,https://shopping-phinf.pstatic.net/main_822861...,254280,,레이바쿠,82286128596,2,꼼데가르송,,패션의류,여성의류,카디건,
8,메종키츠네 <b>가디건</b> 베이비폭스 폭스헤드 더블폭스 칠랙스 [당일출고],https://smartstore.naver.com/main/products/530...,https://shopping-phinf.pstatic.net/main_828471...,267000,,브랜드리퍼블릭,82847151528,2,메종키츠네,메종키츠네,패션의류,여성의류,카디건,
9,허브 R 크롭트 <b>가디건</b>,https://smartstore.naver.com/main/products/115...,https://shopping-phinf.pstatic.net/main_890597...,39700,,사색,89059794147,2,사색,,패션의류,여성의류,카디건,

In [3]:
df.loc[df['lprice']<50000]

,title,link,image,lprice,hprice,mallName,productId,productType,brand,maker,category1,category2,category3,category4
2,봄 가을 간절기 라운드 루즈핏 크롭 <b>가디건</b> 레드 그린 핑크 화이트 블랙...,https://smartstore.naver.com/main/products/546...,https://shopping-phinf.pstatic.net/main_830114...,19900,,ARUMY,83011442056,2,,,패션의류,여성의류,카디건,
3,부드러운 캐시미어 크롭 <b>가디건</b> 숏 라운드 니트<b>가디건</b> 여성 ...,https://smartstore.naver.com/main/products/482...,https://shopping-phinf.pstatic.net/main_823726...,18900,,코이블리,82372678315,2,,,패션의류,여성의류,카디건,
5,시스루 얇은 린넨 루즈핏 니트 여름 여성 <b>가디건</b> (올타임),https://smartstore.naver.com/main/products/559...,https://shopping-phinf.pstatic.net/main_831365...,23900,,고고하니,83136576950,2,,,패션의류,여성의류,카디건,
6,(당일) 프리티영띵 뉴 페블 골지 <b>가디건</b> PYT 프영띵 떠유니,https://smartstore.naver.com/main/products/904...,https://shopping-phinf.pstatic.net/main_865893...,42000,,ttoyuni,86589381117,2,,,패션의류,여성의류,카디건,
9,허브 R 크롭트 <b>가디건</b>,https://smartstore.naver.com/main/products/115...,https://shopping-phinf.pstatic.net/main_890597...,39700,,사색,89059794147,2,사색,,패션의류,여성의류,카디건,

In [7]:
area_50000 = df.loc[df['lprice']>50000]
area_50000.loc[df['mallName'] == '네이버','lprice':'brand']

Empty DataFrame
Columns: [lprice, hprice, mallName, productId, productType, brand]
Index: []

In [9]:
area_50000 = df.loc[df['lprice']>50000]
area_50000

,title,link,image,lprice,hprice,mallName,productId,productType,brand,maker,category1,category2,category3,category4
0,백화점3-5일배송 폴로 <b>가디건</b> 걸즈 걸스 랄프로렌 꽈배기 블랙 화이트 ...,https://smartstore.naver.com/main/products/667...,https://shopping-phinf.pstatic.net/main_842166...,65900,,나우인뉴욕,84216650390,2,폴로랄프로렌,폴로랄프로렌,패션의류,여성의류,카디건,
1,[백화점3-5일배송] 폴로 <b>가디건</b> 니트 걸즈 랄프로렌 블랙 화이트 핑크...,https://smartstore.naver.com/main/products/845...,https://shopping-phinf.pstatic.net/main_859949...,63900,,트위티 155,85994962324,2,폴로랄프로렌,폴로랄프로렌,패션의류,여성의류,카디건,
4,[백화점] 폴로 <b>가디건</b> 걸즈 케이블 꽈배기 니트,https://smartstore.naver.com/main/products/111...,https://shopping-phinf.pstatic.net/main_886518...,69000,,세컨찬스라이프,88651894622,2,폴로랄프로렌,폴로랄프로렌,패션의류,여성의류,카디건,
7,꼼데가르송 기본와펜 <b>가디건</b> 여성용,https://smartstore.naver.com/main/products/474...,https://shopping-phinf.pstatic.net/main_822861...,254280,,레이바쿠,82286128596,2,꼼데가르송,,패션의류,여성의류,카디건,
8,메종키츠네 <b>가디건</b> 베이비폭스 폭스헤드 더블폭스 칠랙스 [당일출고],https://smartstore.naver.com/main/products/530...,https://shopping-phinf.pstatic.net/main_828471...,267000,,브랜드리퍼블릭,82847151528,2,메종키츠네,메종키츠네,패션의류,여성의류,카디건,